### ISSUE TITLE
Typos in aggrid site

### ISSUE THREAD

**Issue by arvyy** [ag-grid/ag-website-shared#1]
https://www.ag-grid.com/javascript-data-grid/licensing/#setting-the-license-key

> then you will a replacement license ky to cover both

presumably should be

> then you will receive a replacement license key to cover both

**Comment by markdurrant** [comment]
Hi @arvyy thanks very much for bring this to our attention. 

This has been fixed in [this commit](https://github.com/ag-grid/ag-grid/commit/a0121c6807b6699a2a9cb8b07efc234c57da3512) and will be deployed shortly. 

For future reference this repo is an internal component library for our websites. Please raise any further issues on our main repository [ag-grid/ag-grid](https://github.com/ag-grid/ag-grid).

**Comment by markdurrant** [comment]
Closing as done.
